/**
 * Curated market horsepower catalog (public docs as of mid-2026).
 * Used by the Market Deep Dive page — separate from the Geoff Thermometer home.
 */

export const marketCatalog = {
  updatedNote:
    "These “quotes” are compiled from public vendor docs. Live status is sniffed separately. Always verify pricing on official pages before you buy tokens or seats.",
  vendors: [
    {
      id: "geoff",
      name: "Geoff / Stacknet",
      company: "Geoff (Artfact / Magma stack)",
      color: "#34d399",
      tagline: "Community compute + multimodal agents",
      delivers: [
        "All-in-one app for chat, image, music, video, voice, code, agents",
        "Shared Stacknet GPU farm (nodes + VRAM pool)",
        "Public /v1/models + widgets + MCP tool surface",
      ],
      horsepower: {
        flagship: "magma",
        context: "Network-routed (varies by model lane)",
        maxContextLabel: "Lane-dependent",
        modalities: ["text", "image", "music", "video", "voice", "code", "agents"],
        apiStyle: "App + Stacknet RPC / OpenAI-compatible /v1/models",
        pricingModel: "App / network usage (preview codes & subscriptions evolving)",
      },
      models: [
        {
          id: "magma",
          role: "Creative powerhouse",
          context: "Network",
          input: "—",
          output: "—",
          notes: "Music, media, agents, multimodal",
        },
        {
          id: "preview",
          role: "Everyday multimodal",
          context: "Network",
          input: "—",
          output: "—",
          notes: "Chat, code, image, tools",
        },
        {
          id: "stack-chat / pyro family",
          role: "Chat & speed lanes",
          context: "Network",
          input: "—",
          output: "—",
          notes: "Multiple network model ids (29+)",
        },
      ],
      research: [
        { label: "geoff.ai", href: "https://geoff.ai" },
        { label: "Stacknet health", href: "https://stacknet.magma-rpc.com/health" },
        { label: "Network summary", href: "https://stacknet.magma-rpc.com/network/summary" },
      ],
    },
    {
      id: "grok",
      name: "Grok",
      company: "xAI",
      color: "#a3e635",
      tagline: "Frontier API with huge context + realtime culture",
      delivers: [
        "Chat Completions-compatible API at api.x.ai",
        "Flagship coding / agentic reasoning models",
        "Imagine (image/video) + Voice APIs alongside text",
      ],
      horsepower: {
        flagship: "grok-4.5",
        context: "500k tokens (flagship)",
        maxContextLabel: "up to ~2M on Fast lanes",
        modalities: ["text", "image", "video", "voice", "code", "tools"],
        apiStyle: "OpenAI-compatible Chat Completions",
        pricingModel: "Usage per 1M tokens (tiered long-context rates)",
      },
      models: [
        {
          id: "grok-4.5",
          role: "Flagship code + agents",
          context: "500k",
          input: "$2.00 / $4.00*",
          output: "$6.00 / $12.00*",
          notes: "*Higher rate when prompt ≥ 200k tokens",
        },
        {
          id: "grok-4.3",
          role: "Long-context reasoning",
          context: "1M",
          input: "$1.25 / $2.50*",
          output: "$2.50 / $5.00*",
          notes: "Strong value reasoning lane",
        },
        {
          id: "grok-4.1-fast / code-fast",
          role: "Cheap high-volume / code",
          context: "2M / 256k",
          input: "~$0.20",
          output: "~$0.50–$1.50",
          notes: "Volume & coding specialists",
        },
      ],
      research: [
        { label: "xAI API", href: "https://x.ai/api" },
        { label: "Models docs", href: "https://docs.x.ai/developers/models" },
        { label: "Console", href: "https://console.x.ai" },
      ],
    },
    {
      id: "openai",
      name: "OpenAI",
      company: "OpenAI",
      color: "#5eead4",
      tagline: "Platform API + frontier GPT / reasoning stack",
      delivers: [
        "Responses / Chat Completions APIs for products & agents",
        "Frontier GPT-5.x family + specialized audio/realtime/image models",
        "Enterprise controls, fine-tunes, and tool ecosystems",
      ],
      horsepower: {
        flagship: "gpt-5.6 Sol",
        context: "up to ~1.05M on GPT-5.x production lanes",
        maxContextLabel: "~1.05M tokens",
        modalities: ["text", "image", "audio", "realtime", "code", "tools", "search"],
        apiStyle: "OpenAI API (Responses + Chat Completions)",
        pricingModel: "Usage per 1M tokens (varies widely by tier)",
      },
      models: [
        {
          id: "gpt-5.6 Sol",
          role: "Highest reasoning ceiling",
          context: "Frontier / preview",
          input: "See docs",
          output: "See docs",
          notes: "Complex pro work, coding, long agents",
        },
        {
          id: "gpt-5.6 Terra / Luna",
          role: "Balanced / cost lanes",
          context: "Frontier / preview",
          input: "See docs",
          output: "See docs",
          notes: "Default vs high-volume cost-sensitive",
        },
        {
          id: "gpt-5.5 / gpt-5.4",
          role: "Stable production",
          context: "~1.05M",
          input: "~$2.50–$5",
          output: "~$15–$30",
          notes: "GA workhorses; Pro tiers much higher",
        },
      ],
      research: [
        { label: "Models catalog", href: "https://platform.openai.com/docs/models" },
        { label: "Pricing", href: "https://openai.com/api/pricing/" },
        { label: "Status", href: "https://status.openai.com" },
      ],
    },
    {
      id: "copilot",
      name: "GitHub Copilot",
      company: "Microsoft / GitHub",
      color: "#86efac",
      tagline: "Multi-model coding cockpit inside the IDE",
      delivers: [
        "Inline + chat + agent coding across VS Code, JetBrains, CLI, github.com",
        "Model picker spanning OpenAI, Anthropic, Google (plan-gated)",
        "Enterprise policy controls for which models orgs can enable",
      ],
      horsepower: {
        flagship: "GPT-5.6 Sol (in Copilot) + Claude Sonnet 5 / Opus lanes",
        context: "Model-dependent (provider windows)",
        maxContextLabel: "Provider max (often 200k–1M+)",
        modalities: ["code", "text", "agents", "repo context", "CLI"],
        apiStyle: "Product UX (not a raw public LLM API)",
        pricingModel: "Seat plans: Free / Pro / Pro+ / Business / Enterprise",
      },
      models: [
        {
          id: "GPT-5.6 Sol / Terra / Luna",
          role: "OpenAI coding tiers",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Sol often gated to higher SKUs",
        },
        {
          id: "Claude Sonnet 5 / Opus 4.x",
          role: "Anthropic coding & agents",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Strong IDE/agent lanes; ZDR on many Sonnets",
        },
        {
          id: "Gemini 3.x Flash / Pro",
          role: "Google speed & pro",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Flash for speed; Pro for heavier reasoning",
        },
      ],
      research: [
        {
          label: "Supported models",
          href: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        },
        { label: "Plans & pricing", href: "https://github.com/features/copilot/plans" },
        { label: "GitHub Status", href: "https://www.githubstatus.com" },
      ],
    },
  ],
  dimensions: [
    {
      id: "api",
      label: "API access coverage",
      blurb: "Can you call models programmatically (Chat Completions-style)?",
      scores: { geoff: "Partial / network", grok: "Yes", openai: "Yes", copilot: "Product only" },
    },
    {
      id: "context",
      label: "Context limits",
      blurb: "How much fits in one prompt/session — your deductible on memory.",
      scores: {
        geoff: "Lane-dependent",
        grok: "500k–2M",
        openai: "~1.05M on GPT-5.x",
        copilot: "Provider window",
      },
    },
    {
      id: "multimodal",
      label: "Multimodal riders",
      blurb: "Add-ons beyond text: image, music, video, voice, realtime.",
      scores: {
        geoff: "Very wide (incl. music)",
        grok: "Text + image/video/voice",
        openai: "Text + image/audio/realtime",
        copilot: "Code-first (+ chat)",
      },
    },
    {
      id: "agents",
      label: "Agent / tools coverage",
      blurb: "MCP, tool calling, IDE agents, sandboxes — who shows up when work gets messy.",
      scores: {
        geoff: "MCP + widgets + sandboxes",
        grok: "Strong tool calling",
        openai: "Tools + Responses agents",
        copilot: "IDE/cloud coding agents",
      },
    },
    {
      id: "price",
      label: "Premium style",
      blurb: "How the bill shows up: tokens, seats, or network credits.",
      scores: {
        geoff: "App / network",
        grok: "$ / 1M tokens",
        openai: "$ / 1M tokens",
        copilot: "Monthly seats",
      },
    },
    {
      id: "transparency",
      label: "Public receipts",
      blurb: "What you can verify without pledging allegiance (or a credit card).",
      scores: {
        geoff: "High — live vitals",
        grok: "Medium — docs, auth API",
        openai: "Medium — status + docs",
        copilot: "Medium — model list, seat fog",
      },
    },
    {
      id: "modularity",
      label: "Modular vs sealed",
      blurb: "Can you strap modules on — or only renew the appliance?",
      scores: {
        geoff: "Strap-on / network",
        grok: "API modules",
        openai: "Platform APIs",
        copilot: "Sealed cockpit",
      },
    },
  ],
};
